name: CI test
on:
    push:
      branches: [ dev ]
    pull_request:
      branches: [ dev ]
jobs:
 build:
  runs-on: ubuntu-latest
  name: Build and Test
  steps:    
        - uses: actions/checkout@master
            name: Checkout Repo
        - uses: actions/setup-node@v1
            name: Create Node Environment
            with: 
              node-version: 12.x          
            name: Install Packages and Build Application
        - run: |
            npm install -g @vue/cli yarn
            yarn install
            yarn build
        - name: Build and Test

